

SELECT * FROM PUBLIC."Fronteirico"
ORDER BY ID ASC

SELECT * FROM PUBLIC."Pais"

SELECT * FROM PUBLIC."Provisorio"
ORDER BY ID ASC

SELECT * FROM PUBLIC."Registro"
ORDER BY ID ASC

SELECT * FROM PUBLIC."Temporario"
ORDER BY ID ASC

SELECT * FROM public."Residente"
ORDER BY id ASC

SELECT * FROM PUBLIC."UF"